
services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - redis
      - mongo
  worker:
    build: .
    command: npm run worker
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo:latest
    restart: always
    ports: 
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: